# Chapitre 1 : Généralités

## I- Introduction

Prise en main du langage Python

In [3]:
# ceci est un test de code 'Hello word'"
'Hello word'

'Hello word'

In [4]:
# afficher ce meme message avec 'print'
print('Hello word')

Hello word


In [5]:
# un autre test 
print("Hello word, je m'appelle Hiver")

Hello word, je m'appelle Hiver


In [8]:
# une fois de plus
print("Hello word,\nje m'appelle Hiver\nje continue de tester")

Hello word,
je m'appelle Hiver
je continue de tester


#### 1 - Python comme calculatrice

In [9]:
# division entière avec //
5//2

2

In [10]:
# puissance avec **
5**2

25

In [11]:
# modulo avec %
5%2

1

##### Dans cette rubrique nous testons les connaissance de python sur l'ordre de priorité des opérateurs de signe dans une opération mathématique : '5+2*-3' ou '2*5**3' et '(2*5)**3'

In [12]:
# ordre de priorité des opératuers
# la multiplication >> addition >> soustraction
5+2*-3

-1

In [13]:
# python réalise d'abord 5**3, puis multiplie par 2
2*5**3

250

In [14]:
# python fait le produit de 2*5 puis élève à la puissance 3
(2*5)**3

1000

In [ ]:
## Exercice 1 : 
# calculer 5 puissance 3 
# ensuite sourtraire 100 du resultat 
# et enfin, diviser le resultat par 5
# la reponse finale doit être = 5 

In [16]:
# corrigé de l'exercice : utiliser les parenthèse pour pour orienter la logique des calculs
(5**3-100)/5

5.0

#### 2 - Types / Classe d'objets Python

In [109]:
# boolean : vrai ou faux
a, b = True, False
print(a)
print(b)

True
False


In [110]:
type(True)

bool

In [17]:
# int : nombre entier
type(7) 

int

In [18]:
# float : nombre décimal
type(3.14)

float

In [19]:
# str : chaine de caratère
type("Mon nom")

str

#### 2 - Les variables
##### Les variables sont des emplacements de mémoires. Les variables sont introduits / initialisées comme en mathématique avec le signe "=". L'utilité est de pouvoir les utiliser dans la suite

##### a) Variable de type nombre

In [35]:
# les varibales d'une équation
x = 3
y = x
y

3

In [ ]:
## Exercice 2 : 
# affecte 19 à la variable z. quel est le type de la variable z? 
# affecte z +1 à la variable z
# affecte z divisé par 5 la variable z
# affecte z puissance 2 à la variable z
# quelle est la valeur de z ? quel est son type ? 

In [53]:
# corrigé de l'exercice : initialisation et réinitialisation de la variable z
z = 19 # type int
type(z)
z+=1
z = z/5
z = z**2
z
type(z) # valeur de z = 16.0

float

In [57]:
# affection multiples
a, b, c = 10, 3, 0
print(a)
print(b)
print(c)

10
3
0


##### b) Variable de type string

In [58]:
# variable de type str
greeting = 'Hello'
print(greeting)

Hello


In [59]:
# + : symbole de concatenation des variables str
greeting + ' world'

'Hello world'

In [60]:
# multilication des chaines de caractères
'Hello'*3

'HelloHelloHello'

In [61]:
# compter la longueur de la chaine de caratère
len(greeting)

5

In [ ]:
## Exercie 3 :
# affecter votre prenom a la variable first_name
# affecter votre nom à la variable last_name (1ere lettre en majiscule)
# transformer la variabele first_name en mettant toutes les lettres en majiscule
# concatener les variables first_name et last_name et affecter le resultat à la variable name
# quel est le nombre de caractère dans la variable name

In [288]:
# corrigé : 
first_name = 'Madison'
last_name = 'Kimia'
last_name = last_name.upper()
print(first_name)
print(last_name)

Madison
KIMIA


In [69]:
# concatenation de variables str
name = first_name + '_' + last_name
print(name)
len(name)

Madison_KIMIA


13

In [73]:
city = 'Brazzaville'
print("je m'appelle", name,"\nJe vis à", city)

je m'appelle Madison_KIMIA 
Je vis à Brazzaville


##### c) Les methodes appliqués aux str

In [289]:
# transformer un texte en texte en majiscule
# méthode .upper()
'Hello world'.upper()

'HELLO WORLD'

In [290]:
# transformer un texte en miniscule 
# méthode .lower()
'Hello World'.lower()

'hello world'

In [291]:
# remplacer des caractères 
# méthode .replace()
'Berty'.replace('erty', 'arthy')

'Barthy'

In [292]:
# transformer la premiere de la phrase en majiscule
# méthode .capitalize()
'madison kimia'.capitalize()

'Madison kimia'

In [293]:
# transformer chaque 1ere lettre de mot en majiscule
# méthode .title()
'josué cyril'.title()

'Josué Cyril'

In [294]:
# fragmenter / séparer une chaine de caractère
# méthode .split()
s = 'la crise sanitaire et financière'
y = 'ce test sur pyhton - je le réussi'

print(s.split())
print(y.split('-'))

['la', 'crise', 'sanitaire', 'et', 'financière']
['ce test sur pyhton ', ' je le réussi']


In [295]:
# séparer des traits d'union une chaine de caratcère
# méthode .join()
p = 'Mama Dina'
'-'.join(p)

'M-a-m-a- -D-i-n-a'

#### 3 - L'indexation

##### L'indexation commence par 0 -  le premier est 0, le dernier est -1

In [296]:
# initialiser la variable region
region = 'Plateaux'

In [86]:
len(region)

8

In [89]:
# premier, deuxieme,... dernier élément
print(region[0])
print(region[1])
print(region[2])
print(region[-1])

P
l
a
x


In [90]:
# élement compris entre plage / intervalle 
print(region[:5])

Plate


In [297]:
# récupérer 'late' dans p-late-aux
print(region[1:5])

late


In [ ]:
## Exercice 4 :
# déclarez la variable city = 'San Francisco'
# récupérez les mots 'San' rt 'Francis' en utilisant l'indexation
# récupérez les 4 premiers éléments et les 4 derniers élément de la variable 

In [95]:
# corrigé : 
city = 'San Francisco'
len(city)

13

In [97]:
# récupérer les variables 
print(city[:3])
print(city[4:11]) 

San
Francis


In [298]:
# récupérer les 4 premiers et derniers variables
p = print(city[:5])
d = print(city[-4:])

San F
isco


#### 4 - La fonction 'input'

##### Fonction permettant d'intérragir avec le programme via un input box

In [105]:
# petit programme avec 'input'
print("comment t'appelles-tu ?")
nom = input()
print('Bonjour', nom)
print("quelle âge as-tu ?")
age = int(input())
print('tu as', age, 'an')

comment t'appelles-tu ?


 Joel


Bonjour Joel
quelle âge as-tu ?


 12


tu as 12 an


## II - Structures conditionnelles et boucles

##### Les opérateurs logiques : True / False

In [ ]:
## Exercie 5 :
# déclarez la variable majeur = True
# déclarez la variable senior = False
# testez :
# majeur and senior
# majeur or senior
# not majeur 
# not senior
# nor majeur and senior 

In [299]:
majeur =  True
senior = False 
# tester la combinaison :
majeur and senior
majeur or senior 
not majeur 
# ainsi de suite...

False

##### Les opérateurs de comparaison : les réponses de ces comparaisons sont de type booléen (True / False)

In [ ]:
# < : inférieur à
# > : supérieur à
# <= : inférieur ou égal à
# >= : supérieur ou égal à
# == : égal / équivalent à
# != : différent de
# le résultat attendu est soit True / False

In [300]:
z = 5
y = 5.0
b = 1000
# z est-il équivalent à y ? 
print('z est-il équivalent à y ? :', z == y)
print('y est-il supérieur ou égal à b ? :', y >= b)
print('y est-il différent de a*b ? :', y != a*b)
# ainsi de suite...

z est-il équivalent à y ? : True
y est-il supérieur ou égal à b ? : False
y est-il différent de a*b ? : True


In [ ]:
## Exercie 6 :
# demandez à un user de rensigner son nom et son âge dans la variable age
# verifiez si l'âge > 18
# vérifiez si l'âge est supérieur ou égal 20 ou inférieur à 25
# vérifiez si l'âge est dans [20 - 30] ou [31 - 40]

In [120]:
# corrigé :
print('quel est ton nom ?')
nom = input()
print(nom, 'quel est ton âge ?')
age = int(input())
# vérification du critère d'âge 
print("l'âge de", nom, "est-il > 18 ? : ", age > 18)

quel est ton nom ?


 Keny


Keny quel est ton âge ?


 16


l'âge de Keny est-il > 18 ? False


In [121]:
# vérifier si l'age apparient à au moins un intervalle
print("lâge de", nom, "est-il dans [20 - 30] ou [31 - 40] ? : ",
      (age >=20 and age <=30) or (age >=31 and age <=40))

lâge de Keny est-il dans [20 - 30] ou [31 - 40] ? :  False


#### 1 - Structure conditionnelle 'if'

In [ ]:
## Exercice 7 : 
# écrire un programme qui conditionne l'age d'un condidat au vote supérieur à 18 an
# et si il a plus de 25 ans, il peut jouer aux jeux du hasard

In [128]:
# corrigé :
age = int(input('quel est ton âge ? :', ))
if age >= 25 :
    print('tu es éligible au vote et aux jeux du hasard')
elif age >= 18 : 
    print('tu es éligible au droit de vote')
else : 
    print('tu es encore trop jeune')

quel est ton âge ? : 20


tu es éligible au droit de vote


In [127]:
# corrigé 2 : usage de if imbriqué (c-a-d : utilisation de 2 fois if)
age = int(input('quel est ton âge ? :', ))
if age >= 18 :
    print('tu es éligible au droit de vote')
    if age >= 25 : 
        print('tu es éligible au vote et aux jeux du hasard')
else : 
    print('tu es encore trop jeune')

quel est ton âge ? : 28


tu es éligible au droit de vote
tu es éligible au vote et aux jeux du hasard


#### 2 - Structure conditionnelle 'for' : itération d'objet

In [130]:
# boucle for avec la fonction range()
# utiliser le pas / incrémentation de 1 (par defaut)
for i in range(1,5):
    print(i)

1
2
3
4


In [141]:
# utiliser l'incrémentation à 2
for i in range(1,5, 2):
    print(i)

1
3


In [142]:
#itérer une chaine de caractère 
for a in 'Python':
    print(a)

P
y
t
h
o
n


In [144]:
# utilisation de for imbriqué
for i in range(3):
    for i in 'bus':
        print(i)

b
u
s
b
u
s
b
u
s


In [ ]:
## Exercice 8 :
# avec une boucle for, obtenez l'affichage ci-dessous : 
# 1 au carré = 1
# 2 au carré = 4
# 3 au carré = 9
#...
#10 au carré = 100

In [153]:
# corrigé :
for i in range(10):
    i+=1
    print(i, 'au carré =', i**2)

1 au carré = 1
2 au carré = 4
3 au carré = 9
4 au carré = 16
5 au carré = 25
6 au carré = 36
7 au carré = 49
8 au carré = 64
9 au carré = 81
10 au carré = 100


In [ ]:
## Exercie 9 : 
# écris la table de multiplication de 9 de 1 à 12

In [154]:
# corrigé :
for i in range (12):
    i+=1
    print('9 *',i,'=',9*i)

9 * 1 = 9
9 * 2 = 18
9 * 3 = 27
9 * 4 = 36
9 * 5 = 45
9 * 6 = 54
9 * 7 = 63
9 * 8 = 72
9 * 9 = 81
9 * 10 = 90
9 * 11 = 99
9 * 12 = 108


#### 3 - Structure conditionnelle 'while'

##### Boucle à utiliser quand le nombre d'itération est inconnu

In [156]:
# affichage des 10 premiers entiers naturels (0,1,2...9)
i = 0 # initialisation de l'itérateur 
while i <= 9:
    print(i)
    i+=1

0
1
2
3
4
5
6
7
8
9


In [ ]:
# NB /  SI LA CONDITION EST MAL DEFINIE, LA BOUCLE TOURNE INDEFINIMENT OU SANS ARRET - BUG...

In [157]:
# utiliser while avec break pour interrompre sinon forcer l'arrêt de l'exécution de l'intruction
i = 1
while i <= 10:
    print(i)
    if i == 6:
        break
    i+=1

1
2
3
4
5
6


In [ ]:
 ## Exercie 10 :
# écrire une boucle while pour afficher les nombre de 0 à 50 en allant par pas de 5
# ecrire le même code en ajoutant le mot clé else

In [159]:
# corrigé :
i = 0
while i <= 50:
    print(i)
    i+=5
else:
    print(i, 'nest pas inférieur à 50')

0
5
10
15
20
25
30
35
40
45
50
55 nest pas inférieur à 50


In [ ]:
## Exercice 11 :
# écrire un code qui détermine si un nombre est pair ou impair

In [164]:
# corrigé :
print('rentrer un nombre :')
n = int(input())
if n%2 == 0:
    print(n, 'est un nombre pair')
else : 
    print(n, 'est un nombre impair')

rentrer un nombre :


 352


352 est un nombre pair


## III - Structure des données 

#### 1 - La liste 

In [ ]:
# structure permettant de stocker des données de divers types. Aussi bien des nombre que des chaine de caractère

In [330]:
# ma premiere liste 
courses = ['farine', 'sucre', 'pattes', 'légumes']
print(courses)
type(courses)

['farine', 'sucre', 'pattes', 'légumes']


list

In [279]:
# indexation
courses[0:2]

['farine', 'sucre']

In [331]:
# concatener plus d'une liste
courses = courses + ['viande', 'lait']
print(courses)

['farine', 'sucre', 'pattes', 'légumes', 'viande', 'lait']


In [281]:
# liste de données de tout type
liste_mixte = ['pop', 23, 3.14, False] + courses
print(liste_mixte)

['pop', 23, 3.14, False, 'farine', 'sucre', 'pattes', 'légumes', 'viande', 'lait']


In [332]:
# ajouter de nouveaux éléments à la liste déjà existante et non vide
# méthode .extend()
courses.extend(['chocolat', 'crème glacée', 'biscuit'])
print(courses)

['farine', 'sucre', 'pattes', 'légumes', 'viande', 'lait', 'chocolat', 'crème glacée', 'biscuit']


In [333]:
# récupérer la position d'un élément 
# methode .index()
position_elem = courses.index('lait')
print(position_elem)

5


In [307]:
# supprimer un élément 
# méthode .pop()
courses.pop(position_elem)
courses # l'élément 'lait' a été supprimé de la liste

['farine',
 'sucre',
 'pattes',
 'légumes',
 'viande',
 'chocolat',
 'crème glacée',
 'biscuit']

In [ ]:
## Exercice 12 :
# vous êtes professeur dans une classe qui compte 8 apprenant, vous voulez effectuer une petite étude sur l'âge de vos élèves
# écrivez un petit programme qui demande à chaque élève de rentrer son âge dans une liste
# calculez l'âge moyen, l'âge médian, le minimum et le maximum de votre effectif 

In [266]:
# corrigé : 
# reflexion : 
# déclarer la variable qui stock l'éffectif de la classe
# de quoi parle le sujet ? - il s'agit d'une étude de la statistique descriptive sur l'âge de la classe
# comment le faire ? - construire une la liste qui se rempli progressivement des âges pour les 8 élèves
# procéder la descriptive

n = 8 # effectif de la classe
age_liste  = []

for i in range (8):
    i+=1
    print('élève',i, '- donne-moi ton âge :')
    age  = int(input())
    age_liste.append(age) # méthode pour ajouter à une liste préalablement vide
age_liste

élève 1 - donne-moi ton âge :


 19


élève 2 - donne-moi ton âge :


 21


élève 3 - donne-moi ton âge :


 22


élève 4 - donne-moi ton âge :


 22


élève 5 - donne-moi ton âge :


 25


élève 6 - donne-moi ton âge :


 28


élève 7 - donne-moi ton âge :


 23


élève 8 - donne-moi ton âge :


 21


[19, 21, 22, 22, 25, 28, 23, 21]

In [179]:
# analyse descriptive sur les âges
# import de la librairie dédiée aux fonctions à utiliser
import statistics as st

In [268]:
# les calculs 
# age moyen : 
print ('age moyen :', round(st.mean(age_liste)))
# age médian :
print('age médian :', st.median(age_liste))
# age minimum et maximum
print('age minimum :', min(age_liste),'\nage maximum :', max(age_liste))

age moyen : 23
age médian : 22.0
age minimum : 19 
age maximum : 28


In [269]:
# trier cette liste par ordre croissant : usage de la fonction sorted()
sorted(age_liste)

[19, 21, 21, 22, 22, 23, 25, 28]

In [ ]:
## Exercie 13 :
# ajouter trois éléments de votre choix à al liste courses
# appliquer la methode .sort() à la liste courses
# afficher la liste courses. quel constat fait ? 

In [334]:
# corrigé :
# rappeler le contenu de la liste
courses

['farine',
 'sucre',
 'pattes',
 'légumes',
 'viande',
 'lait',
 'chocolat',
 'crème glacée',
 'biscuit']

In [335]:
# ajoute de nouveaux éléments
courses.extend(['cahier', 'bloc-note', 'laptop', 'lampe', 'savno'])
courses

['farine',
 'sucre',
 'pattes',
 'légumes',
 'viande',
 'lait',
 'chocolat',
 'crème glacée',
 'biscuit',
 'cahier',
 'bloc-note',
 'laptop',
 'lampe',
 'savno']

In [338]:
# tri de la liste 
# methode .sort()
courses.sort()
courses
# tri qui modifie définitvement l'ordre de la liste à la != de la fonction sorted()

['biscuit',
 'bloc-note',
 'cahier',
 'chocolat',
 'crème glacée',
 'farine',
 'lait',
 'lampe',
 'laptop',
 'légumes',
 'pattes',
 'savno',
 'sucre',
 'viande']

In [340]:
# on remarque une chose !
courses[11]

'savno'

In [ ]:
# il s'agit sans doute du mot 'savon' et non 'savno'
# corriger l'orthographe de l'élément

In [341]:
# corriger / modifier l'orthographe / changer ou remplacer un élément de liste en gardant le même index
correction = courses.index('savno')
courses[correction] = 'savon de toilette'
courses

['biscuit',
 'bloc-note',
 'cahier',
 'chocolat',
 'crème glacée',
 'farine',
 'lait',
 'lampe',
 'laptop',
 'légumes',
 'pattes',
 'savon de toilette',
 'sucre',
 'viande']

In [342]:
# vérifier l'index de la valeur nouvellement remplacée
courses[11]

'savon de toilette'

#### 2 - Le dictionnaire

In [ ]:
# le dictionnaire est une collection de paires clé-valeur 

In [208]:
# création d'un dictionnaire 
auteur = {'nom':'Hiver Segna', 'age':31, 'pays':'congo', 'cours':'python'}
auteur

{'nom': 'Hiver Segna', 'age': 31, 'pays': 'congo', 'cours': 'python'}

In [343]:
# appelle aux clé du dictionnaire
# méthode .keys()
auteur.keys()

dict_keys(['nom', 'age', 'pays', 'cours', 'certificat'])

In [206]:
# récupérer la valeur de la clé 'nom'
auteur['nom']

'Hiver Segna'

In [344]:
# récupérer toutes les valeurs du dictionnaire
# méthode .values()
auteur.values()

dict_values(['Hiver Segna', 31, 'USA', 'python', ['PL-300', 'AZ-504', 'MIT']])

In [210]:
# changer la valeur d'une clé
auteur['pays']='USA'
auteur

{'nom': 'Hiver Segna', 'age': 31, 'pays': 'USA', 'cours': 'python'}

In [217]:
# ajouter une nouvelle paire  clé-valeur
auteur['certificat']=['PL-300', 'AZ-504', 'MIT']
auteur

{'nom': 'Hiver Segna',
 'age': 31,
 'pays': 'USA',
 'cours': 'python',
 'certificat': ['PL-300', 'AZ-504', 'MIT']}

In [ ]:
## Exercice 14 : 
# soit la liste de disctionnaire donnant des informations sur certains grands acteurs de Hollywood
# calculer le revenu moyen des acteurs (en million de dollards)
# afficher les informations des acteurs dont le salaire est supérieur au salaire moyen

In [237]:
# corrigé :
acteurs = [{'acteur' : 'Tom Cruse', 'revenu' : 78.4, 'films': ['Mission impossible', 'Top Gun']},
           {'acteur' : 'Chris Hemsworth', 'revenu' : 82.4, 'films' : ['Vacation', 'Thor', 'Rangnarok']},
           {'acteur' : 'Michael B Jordan', 'revenu' : 76, 'films' : ['Black panther', 'Appolo Crid', 'The Siner']},
           {'acteur' : 'Jackie Chan', 'revenu' :87, 'films' : ['Police story', 'Maitre karate', 'Shaolin', 'Karate kid']},
           {'acteur' : 'Leonardo DiCaprio', 'revenu' : 75, 'films' : ['Titanic', 'le Loup de wall street']}]
acteurs

[{'acteur': 'Tom Cruse',
  'revenu': 78.4,
  'films': ['Mission impossible', 'Top Gun']},
 {'acteur': 'Chris Hemsworth',
  'revenu': 82.4,
  'films': ['Vacation', 'Thor', 'Rangnarok']},
 {'acteur': 'Michael B Jordan',
  'revenu': 76,
  'films': ['Black panther', 'Appolo Crid', 'The Siner']},
 {'acteur': 'Jackie Chan',
  'revenu': 87,
  'films': ['Police story', 'Maitre karate', 'Shaolin', 'Karate kid']},
 {'acteur': 'Leonardo DiCaprio',
  'revenu': 75,
  'films': ['Titanic', 'le Loup de wall street']}]

In [238]:
# corrigé :
# les données actuelles sont dans une liste de dictionnaire - cas non idéal pour les manipuler
# créer donc une liste vide à remplir pour stocker les revenus des acteurs 
revenu = []
for acteur in acteurs:
    r = acteur['revenu']
    revenu.append(r)
revenu

[78.4, 82.4, 76, 87, 75]

In [345]:
# import la librairie idéale pour l'utilisation de la fonction moyenne
import statistics as st

In [239]:
# calcul du revenu moyen 
r_moy = st.mean(revenu)
r_moy

79.76

In [240]:
# écrire la boucle for - si pour afficher ceux dont le revenu est > r_moy
for acteur in acteurs:
    if acteur ['revenu'] > r_moy:
        print(acteur)

{'acteur': 'Chris Hemsworth', 'revenu': 82.4, 'films': ['Vacation', 'Thor', 'Rangnarok']}
{'acteur': 'Jackie Chan', 'revenu': 87, 'films': ['Police story', 'Maitre karate', 'Shaolin', 'Karate kid']}


#### 3 - La Data frame

In [ ]:
# strucure de données en 2D :  ligne et colonne

In [348]:
# importer la librairie de manipulation des dataframes
import pandas as pd

In [ ]:
# ceci veut dire :  appel des fonctions de la librairie pandas - je lui donne pour alias 'pd'
# ainsi, les fonction s'écriront : alias.fonction(). ex : pd.fonction()

In [ ]:
## Exercie 15 :
# créer un dictionnaire pour stocker les notes de 5 élèves (maths, français)
# transformer ce disctionnaire en dataframe 
# transposer la dataframe créée
# les données :  Ryan(18, 16), Elisa(20, 12), Robert(14, 15), Martine(20, 20)

In [347]:
# corrigé :
notes = {'Riyan' : [18, 18], 
         'Elisa' : [20, 12], 
         'Robert' : [14, 15], 
         'Martine' : [20, 20]}
notes

{'Riyan': [18, 18], 'Elisa': [20, 12], 'Robert': [14, 15], 'Martine': [20, 20]}

In [244]:
# transformer le disctionnaire en dataframe 
df = pd.DataFrame(notes)
df

Riyan  Elisa  Robert  Martine
0     18     20      14       20
1     18     12      15       20

In [245]:
# transposer le tableau de données
df = df.T
df

0   1
Riyan    18  18
Elisa    20  12
Robert   14  15
Martine  20  20

In [246]:
# renommer les colonnes 
df.columns = ['Maths', 'Francais']
df

Maths  Francais
Riyan       18        18
Elisa       20        12
Robert      14        15
Martine     20        20

In [248]:
# trouver les indexes de la dataframe 
df.index

Index(['Riyan', 'Elisa', 'Robert', 'Martine'], dtype='object')

In [ ]:
# à la != des listes, dans la df la méthode .index ne donne pas de numéro mais des noms de ligne

In [ ]:
# cette partie 'est qu'une introduction à la dataframe

In [ ]:
## Exercice 16 : 
# Etant donné 2 listes (voir cellule de code ci-desous)
# écrivez un code avec une boucle for qui permet d'avoir l'affichage ci-dessous :
'''
Dada 29
Maryse 30
Dylan 34
Elise 36
Stecy 19
'''

In [252]:
# déclaration de listes
liste_etu = ['Dada', 'Maryse', 'Dylan', 'Elise', 'Stecy'] # liste 1
liste_age = [29,30,34,36,19] # liste 2

In [253]:
# affichage des 2 listes
print(liste_etu)
print(liste_age)

['Dada', 'Maryse', 'Dylan', 'Elise', 'Stecy']
[29, 30, 34, 36, 19]


In [255]:
# corrigé
#on veut rendre le code dynamique - au lieu d'utiliser range(5) : nb liste_age, plutot range(len(x))
for i in range(len(liste_age)):
    print(liste_etu[i], liste_age[i])

Dada 29
Maryse 30
Dylan 34
Elise 36
Stecy 19


## IV - Les fonctions

#### 1 - Les fonctions avec mot clé 'def'

In [353]:
# définition d'une fonction sans argument : fonction statique
# fonction qui renvoi du texte / phrase
def mafonction():
    print('bonjour monsieur/madame\ncomment allez-vous ?')
# appelation de la fonction
mafonction()

bonjour monsieur/madame
comment allez-vous ?


In [354]:
# défition de fonction avec argument : fonction dynamique
def mafonction(nom):
    print('bonjour', nom,'\ncomment allez-vous ?')
mafonction('Bonheur')

bonjour Bonheur 
comment allez-vous ?


In [358]:
# définir une fonction stockée dans une variable
def square(a):
    return a**2
# la fonction ici définie donne le carré du nombre a

In [359]:
# test de la fonction square()
z = square(5) # l'argument a : 5 >>> square(a) = 5**2
z

25

In [360]:
# je multiplie cette variable par 10
z*10

250

In [361]:
# fonction à plus d'un argument
def mafonction(prenom, nom):
    print('bonjour', prenom, nom,'\ncomment allez-vous ?')
mafonction ('Hiver', 'Segna')

bonjour Hiver Segna 
comment allez-vous ?


In [363]:
# définir une fonction qui fait la somme de 2 nombres
def somme(a,b):
    return a+b

In [364]:
# application de la fonction pour les nombre 10 et 20
somme(10,20)

30

In [365]:
## Exercice 17 :
# écrire une fonction qui a 2 arguments et qui retourne la somme de ces 2 arguments si ils sont de meme types
# si les arguments ne sont pas de meme type, la fonction doit retourner la phrase : 
# 'impossible ! les arguments ne sont pas de même type'

In [372]:
# corrigé :
def somme(a, b):
    if type(a) == type(b):
        return a+b
    else:
        print('impossible ! les arguments ne sont pas de même type')

In [373]:
# déclaration de variables a et b
a, b = 5, 7.5
# appel de la fonction
somme(a,b)

impossible ! les arguments ne sont pas de même type


In [374]:
# déclaration de variable 
a = 'uri'
b = 'el'
# appel de la fonction. si le critère est bon, le résultat :  concaténation des 2 variables
somme(a,b)

'uriel'

In [382]:
# fonction qui retourne plusieurs valeurs
def soustraction_deuxsens(x,y):
    valeur1 = x-y
    valeur2 = y-x
    return valeur1, valeur2

In [383]:
# déclaration de variables 
x, y = 3, 10
# appel de la fonction
soustraction_deuxsens(x,y)

(-7, 7)

In [385]:
# véficiation type de la valeur retourné
t = soustraction_deuxsens(x,y)
type(t)

tuple

In [387]:
# récupération des valeurs de cette plage coordonnées (tuple) (-7, 7) 
# affectation des coordonnées aux variables c et d
c, d = t[0], t[1]
print(c)
print(d)

-7
7


#### 2 - Les fonctions avec mot clé 'lambda'

In [ ]:
# les fonction écrit rapidement / à la volée sur une ligne de code

In [389]:
# écrire une fonction qui fait la somme de 2 variables
somme_lambda = lambda a, b : a+b

In [390]:
# déclarer les variable a et b
a, b = 5, 8
# appel de la fonction
somme_lambda(a,b)

13

In [520]:
# les fonction lambda est très bénéfique quand on veut construide des fonctions calculant des objets de liste itérable
# elle se lie à la fonction map()
diplomes = ['bac', 'bts', 'licence', 'master', 'msc', 'ms', 'mba','doctorat']

# construire une fonction qui va transformer tous les éléments de notre liste en majiscule
MAJ_diplomes = map(lambda x: x.upper(), diplomes)
list(MAJ_diplomes)

['BAC', 'BTS', 'LICENCE', 'MASTER', 'MSC', 'MS', 'MBA', 'DOCTORAT']

In [ ]:
## Exercice 18 : 
# A partir de liste nombre = [4,2,5,9,3,10]
# créer une autre liste composée des carrés des éléments de la liste
# utiliser la fonction map() ainsi que le mot clé lambda

In [521]:
# corrigé :
# construire la varialbe liste 
nombre = [4, 2, 5, 9,3 , 10]

#construction de la fonction map(lambda...)
carre = map(lambda x: x**2, nombre)
list(carre)

[16, 4, 25, 81, 9, 100]

In [522]:
# un autre bénéfice d'utiliser lambda c'est de l'associer à ala fonction filter()
staff = ['samwise', 'maonon', 'pierre', 'jude', 'anthony','mayans', 'pan', 'mamy']

# filter tous les noms dont la longueur est supérieur 6
staf_filter = filter(lambda x: len(x)>6, staff) # x constituant les valeurs de la liste staff
list(staf_filter)

['samwise', 'anthony']

## V - Les listes de compréhension

In [403]:
# les liste de compréhension sont des outils qui permettent de créer complexes / calculées

In [407]:
# création d'une liste de compréhension
# voici une liste simple existante
nombre = [10, 20, 30, 40, 50]
# on veut créer une 2e liste contenant les éléments de la première sommés de 5
new_nombre = []
for i in nombre:
    new_nombre.append(i+5)
new_nombre

[15, 25, 35, 45, 55]

In [408]:
# création de la même liste avec une liste de compréhension
new_nombre2 = [i+5 for i in nombre]
new_nombre2

[15, 25, 35, 45, 55]

In [523]:
# vérifions si les 2 listes sont équivalentes
new_nombre == new_nombre2

True

In [ ]:
## Exercice 19 :
# considérant la liste : csi = ['docteur', 'infirmière', 'chercheur', 'sage-femme', 'médecin', 'chrirugien']
# écrire une liste de compréhension qui produit une liste composée de 3 premiers caractères de chaque élément de liste

In [413]:
csi = ['docteur', 'infirmière', 'chercheur', 'sage-femme', 'médecin', 'chirurgien']
new_csi = [i[:3] for i in csi]
new_csi

['doc', 'inf', 'che', 'sag', 'méd', 'chi']

In [ ]:
## Exercice 20 :
# écrire une liste de compréhension qui produit une liste composée des valeurs au carré des éléments de range 10

In [414]:
liste = [i**2 for i in range(10)]
liste

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

## VI - Les librairies

#### 1 - Librairie Numpy

In [ ]:
# Numpy est la librairie utilisée dans des projets de calcul numérique 

In [415]:
# importer la librairie numpy
import numpy as np

##### 1- création des tbl numpy à partir d'une liste

In [491]:
# créer un vecteur à partir d'une liste
v = np.array([1, 2, 3, 4])
v

array([1, 2, 3, 4])

In [417]:
type(v)

numpy.ndarray

In [ ]:
# les tbl numpy sont similaires aux listes - mais avec une foncionnalité supplémentaire 
# réaliser des calculs par éléments unitaires ou aggregés

In [ ]:
## Exercice 21 :
# Vous avez collecter la taille et le poids de chacun de vos coéquipiers.
# les tailles sont stockées dans la liste 'taille' et les poids dans la liste 'poids'
# vous voulez calculer l'indice de masse corporelle 'imc' de chacun.

In [419]:
# corrigé :
# déclaration des variables liste : taille et poids
taille = [1.83, 1.85, 1.64, 1.98, 1.72, 1.89, 1.59, 1.68]
poids = [69, 75, 79, 120, 55, 89, 66, 80]
# vérifier la longueur de chaque liste 
if len(taille) == len(poids):
    print('échantillon équilibré')
else:
    print('les effectifs ne sont pas égaux')

échantillon équilibré


In [420]:
# transformer le sliste en tbl numpy
taille_array = np.array(taille)
poids_array = np.array(poids)

In [422]:
# calcul de l'imc
imc = poids_array/taille_array**2
imc

array([20.60378035, 21.9138057 , 29.37239738, 30.60912152, 18.59113034,
       24.91531592, 26.10656224, 28.3446712 ])

In [423]:
# vérifions les valeurs > 25
imc[imc >25]

array([29.37239738, 30.60912152, 26.10656224, 28.3446712 ])

##### 2- création des tbl numpy à partir des matrices

In [425]:
# déclarons une matrice 'm'
m = np.array([[1, 3], [2, 4]])
print(m)
type(m)

[[1 3]
 [2 4]]


numpy.ndarray

In [524]:
# accéder à un élément de mtrice
print(m[0,1]) # élément à l'intersection de la 1ere ligne, 2e colonne
print(m[:,1]) # élément à l'intersection de toutes les lignes, 2e colonne

3
[3 4]


In [430]:
# revenons compléter l'exercice 21
# maintenant, stockons les tailles et poids dans une matrice 'equipe'
equipe = np.array([taille, poids])
equipe

array([[  1.83,   1.85,   1.64,   1.98,   1.72,   1.89,   1.59,   1.68],
       [ 69.  ,  75.  ,  79.  , 120.  ,  55.  ,  89.  ,  66.  ,  80.  ]])

In [432]:
# chercher la dimension du tableau
equipe.shape

(2, 8)

In [ ]:
## Exercie 22 : 
# déterminer la dimension du tabelau 'm'
# donner la taille et le poids du 2e et 3e coéquipier
# convertir les tailles de la liste en 'cm' et nommer la nouvelle liste taille_cm

In [434]:
# corrigé :
# al dimension du tbl 'm'
m.ndim

2

In [525]:
# la taille et poids du 2e et 3e 
print('2e coéquipier :', equipe[:, 1],'\n3e coéquipier :', equipe[:,2])

2e coéquipier : [ 1.85 75.  ] 
3e coéquipier : [ 1.64 79.  ]


In [437]:
# conversion de la plage taille en 'cm'
taille_cm = taille_array*100
taille_cm

array([183., 185., 164., 198., 172., 189., 159., 168.])

##### 3 - création des tbl numpy à partir des fonctions spéciales

In [438]:
# tbl numpy à partir de la fonction range()
t_range = np.array(range(5))
t_range

array([0, 1, 2, 3, 4])

In [440]:
# méthode 2 : 
t_arange = np.arange(5) # choix plus adapté pour numpy
t_arange

array([0, 1, 2, 3, 4])

In [441]:
# utiliser np.arange pour caler le pas d'incrémentation 
t_arange2 = np.arange(1.0, 2.10, 0.1) # 1.0 : début, 2.10 : borne sup, 0.1 : pas d'incrémentation
t_arange2

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. ])

##### 4- création des tbl numpy à partir de la fonction linspace()

In [ ]:
# linespace() est utilisé quand on veut créer un intervalle avec un nombre précis d'éléments

In [446]:
# usage de la fonction
x = np.linspace(0, 10, 50) # 0 : début, 10 : borne sup, 50 : nb d'élément à créer
x

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

##### 5 - statistiques avec numpy

In [447]:
# revenons compléter l'exercice 22
# rappelons la np.array équipe
equipe

array([[  1.83,   1.85,   1.64,   1.98,   1.72,   1.89,   1.59,   1.68],
       [ 69.  ,  75.  ,  79.  , 120.  ,  55.  ,  89.  ,  66.  ,  80.  ]])

In [451]:
# taille moyenne
taille_moy = np.mean(equipe[0])
# taille médiane
taille_med = np.median(equipe[0])
# écart-type
taille_std = np.std(equipe[0])

# poids moyen
poids_moy = np.mean(equipe[1])
# poids médian
poids_med = np.median(equipe[1])
# écart-type
poids_std = np.std(equipe[1])

In [453]:
print('taille moyenn :', taille_moy)
print('taille médiane :', taille_med)
#...
print('poids moyen :', poids_moy)
print('poids médian :', poids_med)
#...

taille moyenn : 1.7725
taille médiane : 1.775
poids moyen : 79.125
poids médian : 77.0


In [ ]:
## Exercice 23 :
# imaginer une tableau de collecte de données à l'échelle d'une ville
# cette fois, la tableau compte 10000 colonnes et lignes (taille et poids)
# qu'en serait-il à l'échelle d'un département ? d'une région ? d'un pays ou d'un continent ? 
# que faire avec des millions sinon des milliards de ligne ? 

In [455]:
# corrigé :
# simulation de l'exercice 

# générer les données 
taille_city = np.round(np.random.normal(1.76, 0.11, 10000),2)
poids_city = np.round(np.random.normal(79.12, 18.18, 10000), 2)
# génération d'une distribution de taille normale de paramètre mu : moyenne et sigma : son écart-type

In [527]:
# longueur de ligne du tableau
len(taille_city)

10000

In [458]:
# consulter les variables 
print(taille_city)
print(poids_city)

[1.81 1.67 1.96 ... 1.79 1.66 1.65]
[102.33  70.24  65.01 ...  87.31  92.38  44.3 ]


In [460]:
# mettre les tailles en 1ere colonne suivi des poids en 2e colonne
data_city = np.column_stack((taille_city, poids_city))
# appercu de la data
data_city

array([[  1.81, 102.33],
       [  1.67,  70.24],
       [  1.96,  65.01],
       ...,
       [  1.79,  87.31],
       [  1.66,  92.38],
       [  1.65,  44.3 ]])

In [461]:
# statistiques de la data_city
taille_moyen = np.mean(data_city[:,0])
taille_min = np.min(data_city[:,0])
taille_max = np.max(data_city[:,0])

poids_moyen = np.mean(data_city[:,1])
poids_min = np.min(data_city[:,1])
poids_max = np.max(data_city[:,1])

In [466]:
# visualiser les calculs
# calcul de taille
print('taille moyen :', taille_moyen)
print('taille minimum :', taille_min)
print('taille maximum :', taille_max)

# calcul de poids
print('poids moyen :', poids_moyen)
print('poids minimum :', poids_min)
print('poids maximum :', poids_max)

taille moyen : 1.759824
taille minimum : 1.26
taille maximum : 2.15
poids moyen : 79.126113
poids minimum : 9.06
poids maximum : 157.64


##### 6 - les attributs de la librairie numpy

In [469]:
# l'attribut shape retourne la forme du tableau
v = np.array([1, 2, 3, 4])
print(v)
v.shape

[1 2 3 4]


(4,)

In [470]:
# l'attribut ndim pour le nombre de ligne
v.ndim

1

In [471]:
# rappelons la matrice 'm'
m = np.array([[1, 3], [2, 4]])
m.ndim

2

In [492]:
# l'attribut size pour le nb élément
print(v.size)
print(m.size)

4
4


In [481]:
# créeyons une matrice
d2 = np.array([[11, 12, 13], [21, 22, 23]]) # modèle par défaut : 2 lignes, 3 colonnes
d2

array([[11, 12, 13],
       [21, 22, 23]])

In [484]:
# l'attribut reshape pour remodeler la plage de données
d2.shape
# l'argument qu'on passe a reshape est un tuple
v2 = d2.reshape((3,2)) # 3 : nb de ligne, 2 : nb de colonne
v2

array([[11, 12],
       [13, 21],
       [22, 23]])

In [528]:
# méthode ravel : transformer / applatir la plage de données sous forme de vecteur
print(d2)
print(d2.ravel())

[[11 12 13]
 [21 22 23]]
[11 12 13 21 22 23]


#### 2 - Librairie Pandas

In [ ]:
# représentation en mémoire la plus utilisée pour l'importation et l'analyse de données
# c'est la librairie idéale pour manipuler facilement les objets de tableau 

In [494]:
# appeler la librairie 
import pandas as pd

In [529]:
# créeyons un vecteur numpy 
pandas_array =  np.array([100, 5, 20, 80])
pandas_array

array([100,   5,  20,  80])

In [530]:
# formons un tableau de famille
famille_pandas = [[100, 5, 20, 80],
                 [50, 2.5, 10, 40],
                 [110, 6, 22, 80]]
famille_pandas

[[100, 5, 20, 80], [50, 2.5, 10, 40], [110, 6, 22, 80]]

In [543]:
# transformer ce résultat en un tableau numpy
famille_array = np.array(famille_pandas)
print(type(famille_array))
print(famille_pandas)

<class 'numpy.ndarray'>
[[100, 5, 20, 80], [50, 2.5, 10, 40], [110, 6, 22, 80]]


In [499]:
# supposons qu'on veuille obtenir la taille des pattes du pandas indexe de ligne 2
famille_array[2,0]

110.0

In [532]:
# créeyons maintenant une dataframe de la librairie pandas
df_pandas = pd.DataFrame(famille_array)
df_pandas

0    1     2     3
0  100.0  5.0  20.0  80.0
1   50.0  2.5  10.0  40.0
2  110.0  6.0  22.0  80.0

In [533]:
# recréeyons la dataframe avec les noms de lignes et colonnes
df_pandas = pd.DataFrame(famille_array, 
                        columns = ['pattes', 'poiles', 'queue', 'ventre'],
                        index = ['maman', 'bébé', 'papa'])
df_pandas

pattes  poiles  queue  ventre
maman   100.0     5.0   20.0    80.0
bébé     50.0     2.5   10.0    40.0
papa    110.0     6.0   22.0    80.0

In [534]:
# manipuler les données dans la colonne
df_pandas['pattes']

maman    100.0
bébé      50.0
papa     110.0
Name: pattes, dtype: float64

In [545]:
# atteindre un enregistrement spécifique : méthode 1
df_pandas.iloc[2]

pattes    110.0
poiles      6.0
queue      22.0
ventre     80.0
Name: papa, dtype: float64

In [544]:
# atteindre un enregistrement spécifique : méthode 2 (avec nom d'index)
df_pandas.loc['papa']

pattes    110.0
poiles      6.0
queue      22.0
ventre     80.0
Name: papa, dtype: float64

In [537]:
# réaliser un filtre sur la valeur du ventre > 80
# déclarons une variable
filtre = df_pandas['ventre']==80 # le type de valeur renvoyée est booléen
filtre

maman     True
bébé     False
papa      True
Name: ventre, dtype: bool

In [538]:
# réaliser une sélection sur filtre
df_pandas[filtre]

pattes  poiles  queue  ventre
maman   100.0     5.0   20.0    80.0
papa    110.0     6.0   22.0    80.0

In [539]:
# après avoir réalisé le filtre - pour faire une sélection inverse 
df_pandas[~filtre]

pattes  poiles  queue  ventre
bébé    50.0     2.5   10.0    40.0

In [549]:
# ajouter de nouvelles infos dans la famille pandas
qlq_pandas = pd.DataFrame([[105, 4,  19, 80], [100, 5, 20, 80]],
                         columns = df_pandas.columns)
qlq_pandas

pattes  poiles  queue  ventre
0     105       4     19      80
1     100       5     20      80

In [547]:
# concatener les 2 familles
tous_pandas = pd.concat([df_pandas, qlq_pandas])
tous_pandas

pattes  poiles  queue  ventre
maman   100.0     5.0   20.0    80.0
bébé     50.0     2.5   10.0    40.0
papa    110.0     6.0   22.0    80.0
0       105.0     4.0   19.0    80.0
1       100.0     5.0   20.0    80.0

In [ ]:
# on remarque l'indexe 'maman' == l'indexe 1. les valeurs sont les même :  risque de doublons

In [550]:
# nettoyage et suppression des doublons
pandas_uniques = tous_pandas.drop_duplicates()
pandas_uniques

pattes  poiles  queue  ventre
maman   100.0     5.0   20.0    80.0
bébé     50.0     2.5   10.0    40.0
papa    110.0     6.0   22.0    80.0
0       105.0     4.0   19.0    80.0

In [551]:
# ajout d'une nouvelle variable 'sexe'
df_pandas['sexe'] = ['f', 'f', 'm']
df_pandas

pattes  poiles  queue  ventre sexe
maman   100.0     5.0   20.0    80.0    f
bébé     50.0     2.5   10.0    40.0    f
papa    110.0     6.0   22.0    80.0    m

In [554]:
# obtenir les noms de colonnes
print(df_pandas.columns)
# obtenir le nombre de ligne et colonnes
df_pandas.shape

Index(['pattes', 'poiles', 'queue', 'ventre', 'sexe'], dtype='object')


(3, 5)

In [555]:
# méthode .info() : consulter les info de la df
df_pandas.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, maman to papa
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   pattes  3 non-null      float64
 1   poiles  3 non-null      float64
 2   queue   3 non-null      float64
 3   ventre  3 non-null      float64
 4   sexe    3 non-null      object 
dtypes: float64(4), object(1)
memory usage: 252.0+ bytes


In [556]:
# méthode .unique() : pour obtenir les valeurs distincts d'une colonne
df_pandas['sexe'].unique()

array(['f', 'm'], dtype=object)

In [ ]:
# cette partie sur les généralité dans python s'achève - je vais entamer la suite
# l'importation et traitement et visualisation de données pour la data science

# Chapitre 2 : Importation des données

##### Séance de travail typique en Data Science

In [ ]:
# dans ce chapitre, nous allons utiliser un ensemble de données disponible dans la librairie seaborn
# seaborn est une librairie riche en fonctions comme les précédents que nous avons vu
# cette librairie est essentiellement utiliser pour la visualisation, n'empeche que nous utilisons ses jeux de données pour s'entrainer

In [ ]:
# entres autres les données, le cas écheant, nous allons importer les données de naufrage Titanic contenu de cette librairie

In [558]:
# import de la librairie seaborn
import pandas as pd
import seaborn as sns

In [566]:
# chargeons la data
titanic = sns.load_dataset('titanic')
titanic.shape # vérifier les nb lignes et colonnes

(891, 15)

In [568]:
# méthode .head() : afficher les 5 premiers enreg
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [569]:
# méthode .tail() : afficher les 5 derniers enreg
titanic.tail()

survived  pclass     sex   age  sibsp  parch   fare embarked   class  \
886         0       2    male  27.0      0      0  13.00        S  Second   
887         1       1  female  19.0      0      0  30.00        S   First   
888         0       3  female   NaN      1      2  23.45        S   Third   
889         1       1    male  26.0      0      0  30.00        C   First   
890         0       3    male  32.0      0      0   7.75        Q   Third   

       who  adult_male deck  embark_town alive  alone  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True

In [570]:
# créer un échantillon aléatoire 
titanic.sample(5)

survived  pclass     sex   age  sibsp  parch      fare embarked   class  \
268         1       1  female  58.0      0      1  153.4625        S   First   
348         1       3    male   3.0      1      1   15.9000        S   Third   
337         1       1  female  41.0      0      0  134.5000        C   First   
796         1       1  female  49.0      0      0   25.9292        S   First   
635         1       2  female  28.0      0      0   13.0000        S  Second   

       who  adult_male deck  embark_town alive  alone  
268  woman       False    C  Southampton   yes  False  
348  child       False  NaN  Southampton   yes  False  
337  woman       False    E    Cherbourg   yes   True  
796  woman       False    D  Southampton   yes   True  
635  woman       False  NaN  Southampton   yes   True

In [573]:
# modalités distincst des liex d'embarquation
titanic['embark_town'].unique()

array(['Southampton', 'Cherbourg', 'Queenstown', nan], dtype=object)

In [577]:
# procédons à une analyse stat
# appliquons la fonction describe
titanic.describe() # pour inclure toutes les variable, ajouter l'argument : include = 'all'

survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

##### 1- taitement des valeurs manquantes

In [582]:
# méthode 1 : remplir les valeurs manquantes par d'autres valeurs
# déterminer les colonnes où il y a des valeurs manquantes
titanic.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [ ]:
# plusieurs méthodes existe selon la stratégie
# supprimer les NaN que si le nb de données représent un effectif mnégligeable du jeu de données

In [583]:
# méthode .fillna() : remplir les valeurs manquantes par des valeurs != ou == 0.is
titanic_age = titanic.fillna(value = {'age' : 0})
titanic_age.isna().sum()

# remplaçons par la moyenne
titanic_age = titanic.fillna(value = {'age' : titanic['age'].mean()})

In [587]:
# méthode .dropna() : supprimer les lignes ou colonnes contenant les NaN
titanic_age_drop = titanic.dropna()

In [589]:
# consulter le reste de la data après suppression de NaN
titanic_age_drop.shape

(182, 15)

In [ ]:
# NB / PAS BON !!! 
# la suppression des NaN fait perdre plus de 2/3 de l'info du jeu de données

In [590]:
# méthode .drop() : supprimer les colonnes contenant les valeurs manquantes
# retour sur la ligne --> 582 : pour voir les noms des variables portant les NaN

titanic_col_drop = titanic.drop(['age', 'embarked', 'deck', 'embark_town'], 
                                axis = 1) # axis = 1 : colonne ; 0 : ligne

In [591]:
titanic_col_drop.columns

Index(['survived', 'pclass', 'sex', 'sibsp', 'parch', 'fare', 'class', 'who',
       'adult_male', 'alive', 'alone'],
      dtype='object')

In [ ]:
# méthode .dropna() : pour la suppresion de colonnes sans en mentionner les noms
titatic_col_drop = titanic.dropna(axis = 1)

In [593]:
# vérification
titanic_col_drop.isna().sum()

survived      0
pclass        0
sex           0
sibsp         0
parch         0
fare          0
class         0
who           0
adult_male    0
alive         0
alone         0
dtype: int64

In [594]:
titanic_col_drop.shape

(891, 11)

In [ ]:
# on s'est passé de 5 colonnes complètes 

##### 2- renommer une colonne

In [595]:
# rappelons la dataset
# renommer les colonnes

titanic.rename(columns = {'sex' : 'sexe'}, inplace = True)

##### 3- supprimer les lignes et colonnes

In [ ]:
# suprimer une ligne d'indice 0 par ex.
titanic.drop(0).head() #.head() : optionnel - c'est juste pour l'aficjage immédiat

In [ ]:
# supprimer une colonnes
titanic.drop('age', axis = 1).head()

# supprimer plus d'une colonne
titanic.drop(['drop', 'parch'], axis = 1)

##### 4- aggrégation

In [606]:
# un exemple
round(titanic.groupby('pclass')['age'].agg(['mean', 'count']))

mean  count
pclass             
1       38.0    186
2       30.0    173
3       25.0    355

In [609]:
# regouper sur 2 variables
titanic.groupby(['pclass', 'sexe'])['age'].mean()

pclass  sexe  
1       female    34.611765
        male      41.281386
2       female    28.722973
        male      30.740707
3       female    21.750000
        male      26.507589
Name: age, dtype: float64

In [ ]:
## Exercice d'applicaton : analyse caractérisque d'une data voiture

In [ ]:
# lien du fichier de données --> sur github
file = 'https://github.com/Hiver33/basics-python-courses/blob/main/FuelConsumptionCo2.csv'

In [ ]:
# importer les libraires nécessaires

In [ ]:
# importer le fichier de données

In [ ]:
# consulter la data

In [ ]:
# consulter l'info de la data - visualiser le type de données des variables

In [ ]:
# résumé statistique de la data

In [ ]:
# déterminer les valeurs distincs des variables modales

In [ ]:
# créer une dataframe X composée de variables : 
# 'enginesize', 'fuelconsumption_city', fuelconsupmtion_hwy', 'fuelconsumption_comb', 'cylinders'

In [ ]:
# nommer 'y' la variable co2emissions de la data

In [ ]:
# créer un tableau d'aggrégation
# 1 - calculer la stat moyenne sur 'enginesize' groupée par 'vehicleclass'

In [ ]:
# 2 - calculer la stat moyenne sur'enginesize' et 'fuelconsumption_city' groupée par 'make' et 'cynlenders'

In [ ]:
# 3 - calculer la stat moyenne, min et max de 'co2emission' groupée par 'make'et 'cynlenders'